Forma/Forma.Web/Areas/Backoffice/Controllers/ClassController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Forma.Model;
using Forma.Web;
using Forma.Model.ViewModels;

namespace Forma.Web.Areas.Backoffice.Controllers
{
    public class ClassController : CommonController
    {
        // GET: Backoffice/Class
        public ActionResult Index()
        {
            var model = UnitOfWork.Repository<Classes>().GetBy(includes: new List<System.Linq.Expressions.Expression<Func<Classes, object>>> { x => x.Specialization });
            model = model.OrderByDescending(m => m.Id);
                        
            if (this.Request.IsAjaxRequest())
            {
                return PartialView("_ListPartial", model);
            }

            return View(model);
        }
        // GET: Backoffice/Class/Create
        public ActionResult Create()
        {
            var model = new ClassViewModel

            {
                Classes = new Classes(),
                Specialization = UnitOfWork.Repository<Specialization>().GetAll(),
                Responsible = UnitOfWork.Repository<ClassResponsible>().GetAll(),
                Courses = new MultiSelectList(UnitOfWork.Repository<Courses>().GetAll(), "Id", "Name")
              
            };
            return View(model);
        }

        // POST: Backoffice/Class/Create
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(ClassViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                    throw new Exception("Class is not valid!");

                var classes = model.Classes;
                var ids = model.CoursesIds;
                if (ids != null && ids.Length > 0)
                {
                    var courses = new List<Courses>();
                    foreach (var id in ids)
                    {
                        var Course = UnitOfWork.Repository<Courses>().GetById(id);
                        courses.Add(Course);
                    }
                    classes.Courses = courses;
                }

                UnitOfWork.Repository<Classes>().Insert(classes);
                int result = UnitOfWork.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                var viewModel = new ClassViewModel
                {
                    Classes = model.Classes,
                    Specialization = UnitOfWork.Repository<Specialization>().GetAll()
                };
                return View(viewModel);
            }
        }

        // GET: Backoffice/Class/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Backoffice/Class/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Backoffice/Class/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Backoffice/Class/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Forma/Forma.Web/Areas/Backoffice/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Forma.Model;
using Forma.Model.Viewmodels;

namespace Forma.Web.Areas.Backoffice.Controllers
{
    public class DepartmentController : CommonController
    {
        // GET: Backoffice/Department
        public ActionResult Index()
        {
            var model = UnitOfWork.Repository<Department>().GetBy(includes: new List<System.Linq.Expressions.Expression<Func<Department, object>>> { x => x.AcademicYear });
            model = model.OrderByDescending(m => m.Id);

            if (this.Request.IsAjaxRequest())
            {
                return PartialView("_ListPartial", model);
            }

            return View(model);
        }
        // GET: Backoffice/Department/Create
        public ActionResult Create()
        {
            var model = new DepartmentViewModel

            {
                Department = new Department(),
                AcademicYears = UnitOfWork.Repository<AcademicYear>().GetAll()
            };
            return View(model);
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(DepartmentViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                    throw new Exception("Department is not valid!");

                var department = model.Department;

                UnitOfWork.Repository<Department>().Insert(department);
                int result = UnitOfWork.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                var viewModel = new DepartmentViewModel
                {
                    Department = model.Department,
                    AcademicYears = UnitOfWork.Repository<AcademicYear>().GetAll()
                };
                return View(viewModel);
            }
        }
        public ActionResult Edit(Int16? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var model = new DepartmentViewModel
            {
                Department = UnitOfWork.Repository<Department>().GetById(id),
                AcademicYears = UnitOfWork.Repository<AcademicYear>().GetAll()
            };

            if (model == null)
            {
                return RedirectToAction("Index");
            }

            return View(model);
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Edit(DepartmentViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                    throw new Exception("Department is not valid!");

                var originalModel = UnitOfWork.Repository<Department>().GetById(model.Department.Id);

                if (originalModel == null)
                    throw new Exception("Department do not exist!");

                originalModel.Name = model.Department.Name;
                originalModel.Description = model.Department.Description;
                originalModel.AcademicYearId = model.Department.AcademicYearId;
                //originalModel.AcademicYear = model.Department.AcademicYear;

                UnitOfWork.Repository<Department>().Update(originalModel);
                var result = UnitOfWork.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View(model);
            }
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Delete(Int16 id)
        {
            try
            {
                var model = UnitOfWork.Repository<Department>().GetById(id);

                if (model == null)
                    throw new Exception("Department does not exist!");

                UnitOfWork.Repository<Department>().Delete(id);
                var result = UnitOfWork.SaveChanges();

                

                if (this.Request.IsAjaxRequest())
                {
                    return Json(new { state = 1, id = model.Id, message = "Done" });
                }
                else
                {
                    return RedirectToAction("Index");
                }

            }
            catch (Exception)
            {
                

                if (this.Request.IsAjaxRequest())
                {
                    return Json(new { state = 0, id = id, message = "Error" });
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult VirtualDelete(Int16 id)
        {
            try
            {
                var model = UnitOfWork.Repository<Department>().GetById(id);

                if (model == null)
                    throw new Exception("Department does not exist!");

                UnitOfWork.Repository<Department>().VirtualDelete(id);
                int result = UnitOfWork.SaveChanges();

              

                if (this.Request.IsAjaxRequest())
                {
                    return Json(new { state = 1, id = model.Id, message = "Done" });
                }
                else
                {
                    return RedirectToAction("Index");
                }

            }
            catch (Exception)
            {
               

                if (this.Request.IsAjaxRequest())
                {
                    return Json(new { state = 0, id = id, message = "Error" });
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult VirtualUnDelete(Int16 id)
        {
            try
            {
                var model = UnitOfWork.Repository<Department>().GetById(id);

                if (model == null)
                    throw new Exception("Department does not exist!");

                UnitOfWork.Repository<Department>().VirtualUnDelete(model);
                int result = UnitOfWork.SaveChanges();

               

                if (this.Request.IsAjaxRequest())
                {
                    return Json(new { state = 1, id = model.Id, message = "Done" });
                }
                else
                {
                    return RedirectToAction("Index");
                }

            }
            catch (Exception)
            {
               

                if (this.Request.IsAjaxRequest())
                {
                    return Json(new { state = 0, id = id, message = "Error" });
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
        }
    }
}

Forma/Forma.Web/Areas/Backoffice/Controllers/LecturerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Forma.Model;
using Forma.Model.ViewModels;


namespace Forma.Web.Areas.Backoffice.Controllers
{
    public class LecturerController : CommonController
    {
        // GET: Backoffice/Lecturer
       
        public ActionResult Index()
        {
            var model = UnitOfWork.Repository<Lecturer>().GetAll().OrderByDescending(m => m.Created).ToArray();
            
            if (this.Request.IsAjaxRequest())
            {
                return PartialView("_ListPartial", model);
            }

            return View(model);
        }
        // GET: Backoffice/Lecturer/Create
        public ActionResult Create()
        {
            var model =  new LecturerViewModel

            {
                lecturer = new Lecturer(),
                users = UnitOfWork.Repository<ApplicationUser>().GetAll().ToArray()
            };
            return View(model);
        }
        // POST: Backoffice/Lecturer/Create
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(LecturerViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                    throw new Exception("Lecturer is not valid!");

             
                
                //Random rnd = new Random();
                //var getal1 = rnd.Next(100);
                //var getal2 = rnd.Next(100);

                
               // string lecturerNumber =+getal2;
                var lecturer = new Lecturer{ LecturerNumber = "nummer", LecturerEmail = model.lecturer.LecturerEmail, UserId = model.lecturer.UserId };

                //var person = new Person { FirstName = model.Person.FirstName, LastName = model.Person.LastName };
               

                UnitOfWork.Repository<Lecturer>().Insert(lecturer);
                int result = UnitOfWork.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                var viewModel = new LecturerViewModel
                {
                    lecturer = model.lecturer,
                    users = UnitOfWork.Repository<ApplicationUser>().GetAll()
                };
                return View(viewModel);
            }
        }

    }
}

Forma/Forma.Web/Areas/Dashboard/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Forma.Web.Areas.Dashboard.Controllers
{
    public class IndexController : DefaultController //gebruik van defaultController (UnitOFWork)
    {
        // GET: Dashboard/Index
        public ActionResult Index()
        {
            return View();
        }
    }
}

Forma/Forma.Web/Areas/Backoffice/Views/Shared/_Header.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Formata Backoffice", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav"></ul>
        </div>
    </div>
</div>

Forma/Forma.Web/Areas/Backoffice/Views/Shared/_HomeLayout.cshtml
<!doctype html>
<!-- [if lt IE 7]><html dir="ltr" lang="nl-be" class="no-js lt-ie7"><![endif]-->
<!-- [if lt IE 8]><html dir="ltr" lang="nl-be" class="no-js lt-ie8"><![endif]-->
<!-- [if lt IE 9]><html dir="ltr" lang="nl-be" class="no-js lt-ie9"><![endif]-->
<!-- [if lt IE 10]><html dir="ltr" lang="nl-be" class="no-js lt-ie10"><![endif]-->
<!-- [if (gt IE 9)|!(IE)]><!-->
<html dir="ltr" lang="nl-be" class="no-js" prefix="og: http://ogp.me/ns#">
<!--<![endif]-->
<head>
    @* CHARACTER ENCODING *@
    <meta charset="UTF-8">
    @* LATEST VERSION OF RENDERING ENGINE *@
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    @* MOST IMPORTANT SEO FRIENDLY TAG *@
    <title>@ViewBag.Title</title>
    @* OTHER IMPORTANT SEO TAGS *@
    <meta name="description" content="@ViewBag.Description">
    <meta name="keywords" content="@ViewBag.Keywords">
    <meta name="author" content="@ViewBag.Author">
    <meta name="copyright" content="Copyright 2003-15 Arteveldehogeschool. Alle rechten voorbehouden.">
    @* HUMANS AUTHORS TEXT FILE *@
    <link type="text/plain" rel="author" href="~/humans.txt">
    @* FAVICON AND TOUCHICONS ex: http://demosthenes.info/blog/467/Creating-MultiResolution-Favicons-For-Web-Pages-With-GIMP *@
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/content/icons/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/content/icons/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/content/icons/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="~/content/icons/apple-touch-icon-57-precomposed.png">
    <link href="~/content/icons/favicon.ico" rel="icon" type="image/x-icon">
    <link href="~/content/icons/favicon.ico" rel="shortcut icon" type="image/x-icon">
    @* MOBILE VIEWPORT *@
    <meta name="viewport" content="width=device-width">
    @* Backoffice CSS BUNDLE INCLUDE RESET, BOOTSTRAP AND ADMIN STYLES *@
    @Styles.Render("~/Content/css")


    <link rel="stylesheet" type="text/css" href="~/Content/BackOffice/layout.css">

    @* MODERNIZR JS BUNDLE: NEW HTML5 ELEMENTS + FEATURE DETECTION *@
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div id="wrapper" class="active container-fluid">
        <div class="row header-container">
            <div class="col-sm-12 header">
                <div class="row">
                    <div class="col-sm-2 logo">
                        <img src="~/Content/img/logo.png" alt="" />
                    </div>
                    <div class="col-sm-6 header-actions">
                        <a href="#"><i class="glyphicon glyphicon-envelope"></i> Mail</a>
                    </div>
                    <div class="col-sm-4">
                        <ul class="header-navigation ">
                            <li><a href="#">About</a></li>
                            <li><a href="#">FAQ</a></li>
                            <li><a href="#">Contact</a></li>
                            <li>
                                <div class="account clearfix">
                                    <div class="account-picture">
                                        <img src="http://placehold.it/20x20" class="img-circle" />
                                    </div>
                                    <div class="account-name">
                                        <p>Ellen <a href="#"><i class="glyphicon glyphicon-chevron-down"></i></a></p>
                                    </div>
                                    <div class="account-menu hidden">
                                        <ul>
                                            <li>Edit</li>
                                            <li>Logout</li>
                                        </ul>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row content-container">
            <div class="col-sm-2" id="sidebar-wrapper">
                @* Sidebar Partial*@
                @Html.Partial("_Sidebar")
            </div>
            <div class=" col-sm-10" id="page-content-wrapper">
                <!-- Keep all page content within the page-content inset div! -->
                <div class="page-content inset">
                    <div class="row">
                        <div class="col-md-12">
                            <main id="main">
                                @* Render the body of the view *@
                                @RenderBody()
                            </main>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>





    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Forma/Forma.Web/Areas/Backoffice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    @Styles.Render("~/Content/css")
    <link rel="stylesheet" type="text/css" href="~/Content/BackOffice/main.css">
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <div class="body-content">
                    @RenderBody()
                </div>
            </div>
            <div class="col-md-9">
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Forma/Forma.Web/Areas/Backoffice/Views/Shared/_Sidebar.cshtml
@* Sidebar, on the left in the backoffice *@

<ul id="sidebar_menu" class="sidebar-nav">
    <li class="sidebar-brand"><a id="menu-toggle" href="#"><span id="main_icon" class="glyphicon glyphicon-align-justify"></span></a></li>
</ul>
<div class="profile-container">
    <div class="profile-name">
        <h2>Ellen Wagner</h2>
    </div>
    <div class="profile-picture">
        <img src="http://placehold.it/100x100" class="img-circle" />
    </div>
    <div class="profile-account">
        <p><i class="glyphicon glyphicon-edit"></i> Account</p>
    </div>
</div>
<ul class="sidebar-nav" id="sidebar">
    <li>
        <a href="@Url.Action("Index", "AcademicYear")">Academic Year<span class="sub_icon glyphicon glyphicon-chevron-down"></span></a>
        <ul class="collapse-link collapsed">
            <li></li>
        </ul>
    </li>
    <li><a href="@Url.Action("Index", "Department")">Deparments<span class="sub_icon glyphicon glyphicon-chevron-down"></span></a></li>
    <li><a href="@Url.Action("Index", "Specialization")">Specializations<span class="sub_icon glyphicon glyphicon-chevron-down"></span></a></li>
    <li><a href="@Url.Action("Index", "Class")">Classes<span class="sub_icon glyphicon glyphicon-chevron-down"></span></a></li>
    <li><a href="@Url.Action("Index", "User")">Users<span class="sub_icon glyphicon glyphicon-chevron-down"></span></a></li>
    <li><a href="@Url.Action("Index", "Lecturer")">Lecturers<span class="sub_icon glyphicon glyphicon-chevron-down"></span></a></li>
</ul>